<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Version>1.6.0</Version>
    <Authors> CactusPiereysonk,ArchmageTony,bepis69,ShinCFN</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="spt-reflection">
      <HintPath>..\..\..\resources\spt-reflection.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\resources\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>..\..\..\resources\Comfort.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Comfort.Unity">
      <HintPath>..\..\..\resources\Comfort.Unity.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ItemComponent.Types">
      <HintPath>..\..\..\resources\ItemComponent.Types.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\resources\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\resources\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\..\resources\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
